Update nights
TripSplit/TripSplit pull request #13
Opened 2022-08-16 17:29 UTC by K-Ramos

I tested it with the changes in main and it works so far.

Checkboxes are looking good

2022-08-16 18:24 UTC, rakmo97 commented
@K-Ramos Names of people added during redistribution setup don't display in the redistribution summary printout.

2022-08-16 18:37 UTC, rakmo97 requested changes

2022-08-16 18:37 UTC, rakmo97 commented on JavaScript/siteLogic.js
> +                console.log(orgNights[index]);
@K-Ramos Do we need the console.logs here? Do you think it should stay for the future or should we delete these lines?

2022-08-16 18:37 UTC, rakmo97 commented on JavaScript/test
> +1. Write a program to find the minimum node element in a Linked List.
What is this program for?

2022-08-16 18:37 UTC, rakmo97 commented on docs/JavaScript/test
> +1. Write a program to find the minimum node element in a Linked List.
Same? Do we need it? Or the docs folder?

2022-08-16 18:37 UTC, rakmo97 commented on index.html
>           -If your friends changed their plans after everything was paid for, you may now follow the same steps above to make changes. This includes adding more people and changing nights
Should do some styling or something for this line. It trails of the side. Let's see if we can wrap the text somehow.

2022-08-16 19:09 UTC, akbatt3n commented on index.html
>           -If your friends changed their plans after everything was paid for, you may now follow the same steps above to make changes. This includes adding more people and changing nights
The <pre> tag makes it so the text is displayed exactly as typed, no wrapping. Add "white-space: pre-wrap;" to the CSS or style attribute.

2022-08-16 20:52 UTC, K-Ramos commented on index.html
>           -If your friends changed their plans after everything was paid for, you may now follow the same steps above to make changes. This includes adding more people and changing nights
lets work that in another issue. We need to get this branch merged so that multiple people can goi change things

2022-08-16 20:52 UTC, K-Ramos commented on docs/JavaScript/test
> +1. Write a program to find the minimum node element in a Linked List.
that shouldn't be there. My mistake lol

2022-08-16 20:54 UTC, K-Ramos commented
Removed console log lines and fixed the adding issie

2022-08-17 15:49 UTC, rakmo97 commented
@K-Ramos Changes made to original attendee nights aren't accounted for in redistribution calculations.

2022-08-17 19:14 UTC, rakmo97 approved these changes

2022-08-17 19:19 UTC, merged